# Generated by Django 4.1.7 on 2023-03-17 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Kanban", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todochild",
            options={"verbose_name": "Спиоск дел", "verbose_name_plural": "Сипсок дел"},
        ),
    ]
