# Generated by Django 4.1.6 on 2023-03-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0002_alter_todochild_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todochild',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='todochild',
            name='description',
            field=models.TextField(help_text='Enter a todo description', max_length=255, null=True),
        ),
    ]
