# Generated by Django 4.1.6 on 2023-03-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0003_todochild_creation_date_todochild_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todochild',
            name='creation_date',
            field=models.DateField(null=True),
        ),
    ]
