# Generated by Django 4.1.6 on 2023-03-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0004_alter_todochild_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todochild',
            name='creation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
